permalink: /:categories/:title/
url: "https://luminousvibe.github.io/the-life-of-fetzig/"
full_name: "LuminousVibe"
first_name: "The Life of Fetzig"
last_name: 
blog_title: "The Life of Fetzig"
author_img_name_path: "/images/users/user.jpg"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "An adventure in illness, madness, and entering society."
